apiVersion: v1
kind: PersistentVolume
metadata:
  name: static
spec:
  storageClassName: "standard"
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # this path needs to exist on the host machine.
    path: /home/docker/static/
    type: Directory
