# Generated by Django 4.1.2 on 2024-02-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="room_ids_with_unread_messages",
            field=models.TextField(default="[]"),
        ),
    ]
