# Generated by Django 4.1.2 on 2024-03-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0003_user_room_ids_with_unread_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="room_ids_with_unread_messages",
            field=models.JSONField(default=[]),
        ),
    ]
