# Generated by Django 4.1.2 on 2023-03-06 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0001_initial"),
        ("custom_user", "0003_user_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="country.countrycode",
            ),
        ),
    ]
