# Generated by Django 4.1.2 on 2023-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0004_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("dark", "dark"), ("light", "light")],
                default="dark",
                max_length=254,
            ),
        ),
    ]
