# Generated by Django 4.1.2 on 2023-03-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0005_user_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="units",
            field=models.CharField(
                choices=[("kilometers", "kilometers"), ("miles", "miles")],
                default="miles",
                max_length=254,
            ),
        ),
    ]
