# Generated by Django 4.1.2 on 2024-07-10 14:24

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_user",
            "0005_user_search_country_user_search_genres_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                default=django.contrib.gis.geos.point.Point([]),
                srid=4326,
            ),
        ),
    ]
