# Generated by Django 4.1.2 on 2023-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0006_user_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_units",
            field=models.CharField(
                blank=True,
                choices=[("kilometers", "kilometers"), ("miles", "miles")],
                default=None,
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="units",
            field=models.CharField(
                choices=[("kilometers", "kilometers"), ("miles", "miles")],
                default="kilometers",
                max_length=254,
            ),
        ),
    ]
