# Generated by Django 4.1.2 on 2023-03-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0007_user_preferred_units_alter_user_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
    ]
