# Generated by Django 4.1.2 on 2024-08-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0008_user_instruments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="location",
            new_name="point",
        ),
    ]
