# Generated by Django 4.1.2 on 2023-03-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0007_alter_gig_country"),
        ("custom_user", "0008_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="gig.genre"
            ),
        ),
    ]
