# Generated by Django 4.1.2 on 2023-03-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genre", "0001_initial"),
        ("custom_user", "0009_user_bio_user_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="genre.genre"
            ),
        ),
    ]
