# Generated by Django 4.1.2 on 2024-08-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0010_user_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_band",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_looking_for_band",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_looking_for_musicians",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_musician",
            field=models.BooleanField(default=False),
        ),
    ]
