# Generated by Django 4.1.2 on 2024-08-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0011_user_is_band_user_is_looking_for_band_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="search_instruments",
            field=models.TextField(null=True),
        ),
    ]
