# Generated by Django 4.1.2 on 2023-08-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0011_notificationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="user"),
        ),
        migrations.AddField(
            model_name="user",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="user"),
        ),
    ]
