# Generated by Django 4.1.2 on 2023-09-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0010_gig_thumbnail"),
        ("custom_user", "0013_user_favorite_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_gigs",
            field=models.ManyToManyField(
                related_name="favourite_for_users", to="gig.gig"
            ),
        ),
    ]
