apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
spec:
  storageClassName: "do-block-storage"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: dobs.csi.digitalocean.com
    volumeHandle: ${volume_id}
    fsType: ext4
