apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: docker.io/royhanley8/gp_be:latest
        volumeMounts:
        - mountPath: /code/project/media/
          name: media
        - mountPath: /code/project/static/
          name: static
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "project.settings.local"
        - name: SECRET_KEY
          value: "#m£ow!"
        - name: CELERY_BROKER_URL
          value: "redis://cache:6379/2"
        - name: SERVER_ADDRESS  # Needed to avoid CSRF/CORS errors.
          value: "http://192.168.49.2:31643"
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      - name: static
        persistentVolumeClaim:
          claimName: static
      imagePullSecrets:
      - name: regcred
