apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # this path needs to exist on the host machine.
    path: /var/lib/docker/volumes/minikube_database/
