apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache-container
        image: docker.io/royhanley8/redis-roy:latest
        volumeMounts:
        - mountPath: /data
          name: redis
      volumes:
      - name: redis
        persistentVolumeClaim:
          claimName: redis
      imagePullSecrets:
      - name: regcred
