# Generated by Django 4.1.2 on 2023-02-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("country", models.CharField(max_length=254, unique=True)),
                ("code", models.CharField(max_length=2, unique=True)),
                ("rank", models.IntegerField(default=2)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
