# Generated by Django 4.1.2 on 2023-03-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("genre", models.CharField(max_length=254, unique=True)),
                ("rank", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
