# Generated by Django 4.1.2 on 2023-11-24 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audio", "0001_initial"),
        ("genre", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="albums", to="genre.genre"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="gig",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Gig this album is linked to. This maybe "
                    "empty if linked to a profile."
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gig.gig",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Profile this album is linked to. "
                    "This maybe empty if linked to a gig."
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
