# Generated by Django 4.1.2 on 2023-09-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0002_alter_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="album_thumbnails"
            ),
        ),
        migrations.AddField(
            model_name="audio",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="audio_thumbnails"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="album_images"
            ),
        ),
    ]
