# Generated by Django 4.1.2 on 2023-09-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genre", "0001_initial"),
        ("audio", "0003_album_thumbnail_audio_thumbnail_alter_album_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="albums", to="genre.genre"
            ),
        ),
    ]
