# Generated by Django 4.1.2 on 2023-09-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0004_album_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="position",
            field=models.IntegerField(
                default=1, help_text="position in album"
            ),
            preserve_default=False,
        ),
    ]
