# Generated by Django 4.1.2 on 2023-09-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0005_audio_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_tracks",
                to="audio.album",
            ),
        ),
    ]
