# Generated by Django 4.1.2 on 2023-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0006_alter_audio_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
