# Generated by Django 4.1.2 on 2024-07-04 14:15

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="search_gig_country",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="search_gig_description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="search_gig_genres",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="search_gig_location",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="search_gig_title",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="search_members",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="search_username",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
