# Generated by Django 4.1.2 on 2023-05-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_room_members_alter_room_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="message",
        ),
    ]
