# Generated by Django 4.1.2 on 2023-07-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_notificationtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationToken",
        ),
    ]
