# Generated by Django 4.1.2 on 2023-11-24 11:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country", "0001_initial"),
        ("genre", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gig",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="title, artist, band or festival",
                        max_length=254,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "location",
                    models.CharField(
                        help_text="Venue, pub, warehouse or location",
                        max_length=254,
                    ),
                ),
                ("has_spare_ticket", models.BooleanField(default=False)),
                ("start_date", models.DateTimeField()),
                (
                    "end_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="gig"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="gig"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gigs",
                        to="country.countrycode",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="gigs", to="genre.genre"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gigs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
