# Generated by Django 4.1.2 on 2024-07-04 13:17

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
