# Generated by Django 4.1.2 on 2023-02-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="gig",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
