# Generated by Django 4.1.2 on 2024-07-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0002_gig_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="search_country",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="gig",
            name="search_genres",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="gig",
            name="search_username",
            field=models.CharField(max_length=254, null=True),
        ),
    ]
