# Generated by Django 4.1.2 on 2023-02-14 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0001_initial"),
        ("gig", "0003_genre_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="artist",
            field=models.CharField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gig",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gigs",
                to="country.countrycode",
            ),
        ),
        migrations.AddField(
            model_name="gig",
            name="has_spare_ticket",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="gig",
            name="genre",
        ),
        migrations.AddField(
            model_name="gig",
            name="genre",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="gigs", to="gig.genre"
            ),
        ),
    ]
