# Generated by Django 4.1.2 on 2024-08-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0003_gig_search_country_gig_search_genres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="is_free_gig",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gig",
            name="looking_for_gigpig",
            field=models.BooleanField(default=False),
        ),
    ]
