# Generated by Django 4.1.2 on 2023-02-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0004_gig_artist_gig_country_gig_has_spare_ticket_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gig",
            old_name="genre",
            new_name="genres",
        ),
    ]
