# Generated by Django 4.1.2 on 2023-03-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0005_rename_genre_gig_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gig",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="gig",
            name="venue",
        ),
        migrations.AlterField(
            model_name="gig",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="gigs", to="gig.genre"
            ),
        ),
        migrations.AlterField(
            model_name="gig",
            name="location",
            field=models.CharField(
                help_text="Venue, pub, warehouse or location", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="gig",
            name="title",
            field=models.CharField(
                help_text="title, artist, band or festival", max_length=254
            ),
        ),
    ]
