# Generated by Django 4.1.2 on 2023-03-10 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0001_initial"),
        (
            "gig",
            "0006_remove_gig_artist_remove_gig_venue_alter_gig_genres_and_more",  # noqa
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gig",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gigs",
                to="country.countrycode",
            ),
        ),
    ]
