# Generated by Django 4.1.2 on 2023-03-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0010_alter_user_genres"),
        ("genre", "0001_initial"),
        ("gig", "0007_alter_gig_country"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.AlterField(
            model_name="gig",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="gigs", to="genre.genre"
            ),
        ),
    ]
