# Generated by Django 4.1.2 on 2023-08-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gig", "0009_gig_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="gig"),
        ),
    ]
